services:
  - type: web
    name: resume2portfolio-api
    env: python
    region: oregon
    plan: free
    runtime: python-3.9
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: FRONTEND_URL
        value: https://leninathikam.github.io
